language: ruby

rvm:
 - 2.0.0

script:
 - bundle exec rake -f taudinpurkauspeli/Rakefile db:migrate --trace
 - RAILS_ENV=test bundle exec rake -f taudinpurkauspeli/Rakefile db:migrate --trace
 - bundle exec rake -f taudinpurkauspeli/Rakefile db:test:prepare
 - bundle exec rspec -fd taudinpurkauspeli/spec/
