local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

staging:
  service: Disk
  root: <%= ENV['TAUDINPURKAUSPELI_STORAGE_PATH'] %>

production:
  service: Disk
  root: <%= ENV['TAUDINPURKAUSPELI_STORAGE_PATH'] %>