Exercise.create!([
  {name: "Taudinpurkaus lihanautakasvattamossa", anamnesis: "Ison lihakarjatilan emäntä soittaa sinulle iltapäivällä 11. elokuuta, koska tilan eläinkuolleisuus on noussut. Tilalla on noin 300 nautaa jaettuna useampaan kasvattamorakennukseen. Keskimääräinen kuolleisuus tilalla on ollut korkeintaan 1 nauta/kuukausi. Tänä aamuna, 11. elokuuta oli kuollut kuitenkin 12 nautaa, ja aamupäivän aikana ennen sinulle soittamista on kuollut 15 nautaa lisää. \r\nSinun tehtävänäsi on selvittää nautojen kuolinsyy mahdollisimman nopeasti ja estää toimenpiteilläsi uudet kuolintapaukset ja muut tappiot tilalla. Mitä teet ja missä järjestyksessä?", hidden: false},
  {name: "Taudinpurkaus lypsykarjassa", anamnesis: "Lypsykarja on sairastunut äkillisesti. Sinun tehtävänäsi on selvittää nautojen kuolinsyy mahdollisimman nopeasti ja estää toimenpiteilläsi uudet kuolintapaukset ja muut tappiot tilalla. Mitä teet ja missä järjestyksessä?", hidden: true}
])
ExerciseHypothesis.create!([
  {exercise_id: 1, hypothesis_id: 22, explanation: "Suu- ja sorkkataudin aiheuttaa picornavirus. Virukset eivät aiheuta äkkikuolemia naudalla. Eläimillä ei ole kuumetta, ontumaa eikä rakkuloita suussa ja/tai sorkkaväleissä. Mutta tietysti tarkastat nämä kliinisen tutkimuksen avulla.", task_id: 5},
  {exercise_id: 1, hypothesis_id: 3, explanation: "BSE:n tapauksessa kuolemat ovat yksittäistapauksia, toisin kun nyt. Eläinten käytöksessä ei ole ilmennyt pidemmällä aikavälillä mitään poikkeavaa (epänormaalia kiihtymystä tai poikkeavaa reagoimista ärsykkeisiin) ennen niiden kuolemaa.", task_id: 5},
  {exercise_id: 1, hypothesis_id: 8, explanation: "IBR aiheuttaa hengitystieoireita tai genitaalialueen tulehduksia, eikä kuolemia.", task_id: 5},
  {exercise_id: 1, hypothesis_id: 6, explanation: "Eläimillä ei ollut oireena ripulia.", task_id: 5},
  {exercise_id: 1, hypothesis_id: 18, explanation: "Eläimillä ei ollut hengitystieoireita.", task_id: 5},
  {exercise_id: 1, hypothesis_id: 10, explanation: "Laidunkouristus on tyypillinen alkukesästä, kun naudat saavat nuorta, tuoretta ruohoa. Sairautta esiintyy eniten lypsylehmillä, joskin se on mahdollista myös lihakarjalla. Niukka magnesiumpitoisuus ja väärä Ca/Mg -suhde altistavat. Tässä tapauksessa kivennäisruokinta on kuitenkin kunnossa. Lisäksi päivystävän eläinlääkärin antama magnesium ei ollut auttanut yhtään.", task_id: 5},
  {exercise_id: 1, hypothesis_id: 19, explanation: "Hypokalsemia on yksilöongelma. Sitä esiintyy vastapoikineilla lehmillä, joita ei tässä tapauksessa ollut. Kivennäisruokinta oli kunnossa.", task_id: 5},
  {exercise_id: 1, hypothesis_id: 2, explanation: "B-vitamiinin puutos ei aiheuta joukkokuolemia.", task_id: 5},
  {exercise_id: 1, hypothesis_id: 12, explanation: "Liika väkirehun syöminen ei yleensä koske näin isoa joukkoa eläimiä, vaan yleensä joitakin yksilöitä, jotka ovat päässeet karkaamaan väkirehuvarastoon tai viljapeltoon ja se tulisi yleensä esiin jo puhelussa. Jos väkirehun syöttölaitteisto on rikkoontunut, omistaja olisi myös yleensä huomannut sen. Lisäksi liian väkirehun syömisen oireet ovat erilaiset: ensimmäisenä päivänä ylensyömisen jälkeen lehmä on syömätön (saattaa puhaltua), toisena jalaton ja kolmantena hengetön - siis ilman hoitoa.", task_id: 5},
  {exercise_id: 1, hypothesis_id: 23, explanation: "Sähköisku tappaa heti. Näillä naudoilla oli edeltäviä oireita. Rakenteisiin päässyttä sähköä voisi mitata jännitemittareilla, mutta nyt ei ole edes siihen syytä.", task_id: 5},
  {exercise_id: 1, hypothesis_id: 25, explanation: "Vierasesine rehussa aiheuttaa erittäin harvoin ensinnäkään epidemiaa (poikkeuksena, jos rehuun on silputtu piikkilanka-aitaa ja sitä rehua syötetty usealle) ja lisäksi se ei aiheuta näin nopeasti kuolemia. Joskus harvoin on esiintynyt yksittäinen äkkikuolema, jos rehussa ollut terävä naula on pistänyt verkkomahasta suoraan sydämeen. Muut vierasesineet (muovit, köydet, yms) ovat yksittäisen naudan sairauksia, eivätkä aiheuta tällaisia kuolemia tai edes oireita.", task_id: 5},
  {exercise_id: 1, hypothesis_id: 1, explanation: "Aujeszkyn tauti on herpesviruksiin kuuluvan pseudorabiesviruksen aiheuttama virustauti, jota ei ole tavattu Suomessa. Se on ensisijaisesti sikojen tauti ja muilla eläimillä harvinainen, mutta johtaa kuolemaan. Naudalla oireisiin kuuluvat ihon kutina (ulserat ja sekundaariset infektiot raapimisen seurauksena), paralyysi ja suhteellisen nopea kuolema. Näillä naudoilla ei ollut kutinaoireita eikä paralyysiä, eikä kontakteja ulkomaisiin sikoihin.", task_id: 8},
  {exercise_id: 1, hypothesis_id: 4, explanation: "Jopa 70 - 90 % BVD -tartunnoista arvioidaan olevan oireettomia. Akuutille BVD:lle tyypillisiä oireita ei tilalla esiintynyt kuten kuumetta, alakuloisuutta, ruokahaluttomuutta, , syöpymiä tai haavaumia suussa tai ripulia. Pysyvästi infektoituneilla vasikoilla tietyssä olosuhteissa on muualla maailmassa esiintynyt ns. mucosal disease –tautia (MD), joka syntyy, kun viruserittäjän oma virus muuntuu tai viruserittäjä saa muuntuneen viruksen aiheuttaman tartunnan. MD esiintyy tavallisimmin 6 - 18 kk:n ikäisillä viruserittäjillä joko akuutissa tai kroonisessa muodossa. Akuutissa MD:n oireina ovat muun muassa kuume, ruokahaluttomuus, voimakas vetinen ja joskus verinen ripuli, sierain- ja silmävuoto, sarveiskalvon sameus ja lisääntynyt syljen eritys. Lisäksi suun ja nielun limakalvoilla, sorkkien väleissä sekä vetimien ja häpyhuulten iholla voi esiintyä syöpymiä. Akuutti MD johtaa kuolemaan 3-10 päivässä. ", task_id: 9},
  {exercise_id: 1, hypothesis_id: 16, explanation: "Eläimet eivät ole kuumeisia. Kuolleiden eläinten peräaukosta tai muista ruumiinonteloista ei valu tummaa, hyytymätöntä verta. Lihansyöjät eivät ole herkkiä pernarutolle, joten pernarutto ei selitä koiran oireita.", task_id: 8},
  {exercise_id: 1, hypothesis_id: 9, explanation: "Kinokuumeessa voi olla akuutti taudinkulku, mutta yleensä kuolema ei ole yhtä akuutti kuin tässä tapauksessa. Tapauksen eläimillä ei ole kuumetta, turvotusta silmien alueella, valonarkuutta ja ennen kaikkea niillä ei ole ollut läheistä kontaktia lampaiden kanssa. Kinokuume ei tartu naudasta toiseen, vaan ainoastaan lampaasta nautaan. Tartunnat ovat yleensä yksittäistapauksia.", task_id: 8},
  {exercise_id: 1, hypothesis_id: 24, explanation: "Eläimillä ei havaittu syviä haavoja, joiden kautta tartunta olisi voinut tapahtua. Eläimiä ei ole kastroitu tai niille ei ole tehty muita kirurgisia toimenpiteitä. Eivätkä oireetkaan sovi tetanukseen. - Tetanuksen inkubaatioaika on 2-3 päivästä useampaan viikkoon. Lihansyöjät (koira) eivät ole herkkiä tetanukselle. Myöskään oireet eivät sovi jäykkäkouristukseen, jossa oireet puhkeavat 2 viikon -1 kuukauden kuluttua inokulaatiosta: puhaltuminen  (tyypilliset ratisevat pötsiäänet, kuin herneitä tiputeltaisiin, tai kaikuvia ääniä), jäykkyys, sahapukkiasento ja vatsalihasten jännittyminen (ampiaisvyötärö). Häntä on jäykkä ja vähän koholla, ilme hätääntynyt, korvat sojottavat, kolmas silmäluomi on esillä (ei aina naudalla), syljeneritys on lisääntynyt ja eläin on ärtyvä. Sairastunut eläin vetää helposti ruokaa henkitorveen. Leukalukko on patognomoninen oire, joka havaitaan usein vasta, kun sairasta ja syömätöntä eläintä ruvetaan letkuttamaan. Tetanus on tässä luokiteltu infektiotaudiksi, koska vaikka bakteeri on saatu maaperästä jonkun ympäristössä olleen pistävän asian takia, bakteeri lisääntyy haavassa tuottaen toksiinia. Ihmisillä tetanus on aiheutunut mm. koiran puremasta tai ruusunpiikin pistosta, joten aina haavan ei tarvitse olla syväkään.", task_id: 8},
  {exercise_id: 1, hypothesis_id: 5, explanation: "Botulismin aiheuttaa ruokamyrkytystä aiheuttava Clostridium botulinum -bakteeri. Eläin saa taudin syötyään valmista myrkkyä. Bakteeri kasvaa neutraalissa tai alkaalisessa ympäristössä. Sairastumisen aiheuttaa yleensä saastunut rehu, eläinten raadot tai mätänevä kasvusto. Jättipaalit ovat selkeä riski, varsinkin jos rehu on puitu läheltä maanpintaa eikä happoa ole käytetty. Taudin inkubaatioaika on vuorokaudesta viikkoon. Oireena on heikkous, kraniaalisesti etenevä horjuvaa kävely, lisääntynyt syljeneritys, puremalihasten ja kielen halvaus sekä puhaltuminen. Myrkytys ei yleensä koskisi näin suurta joukkoa. Diagnoosi tehdään anamneesin ja kliinisten oireiden perusteella. Raadonavauksessa pitäisi näkyä patognomonisia muutoksia. Hoito olisi oireiden mukaista, mutta käytännössä todennäköisesti botulismia sairastava nauta olisi lopetettava heti. On kuvattu tapauksia, jotka olisivat hyvällä yleishoidolla saatu paranemaan. Ruho ei kelpaa elintarvikkeeksi. - Tämän tilan rehu oli lisäksi hyvälaatuista. Jos oikeasti epäilisi botulismia, verinäyte, mahansisältöä ja epäiltyä rehua pitäisi pakastaa ja toimittaa Eviraan, joka toimittaa ne edelleen ulkomaille tutkittavaksi.", task_id: 8},
  {exercise_id: 1, hypothesis_id: 17, explanation: "Säilörehu oli raikkaan hapokkaan tuoksuista, eikä siinä näkynyt eläinten raatoja. Rehu ei siis vaikuttanut ollenkaan pilaantuneelta. Lisäksi pilaantunut rehu ei aiheuta tällaisia oireita.", task_id: 8},
  {exercise_id: 1, hypothesis_id: 7, explanation: "Hypertermia on naudoillakin mahdollinen, mutta ei yleinen. Naudat kestävät lämpimiä olosuhteita, mikäli niiden vedensaannissa ei ole mitään poikkeavaa. Tilalla ei ole ollut mitään poikkeavaa vedensaannin suhteen kuolemantapausten aikaan.", task_id: 8},
  {exercise_id: 1, hypothesis_id: 13, explanation: "Osastoissaan lehmät eivät ole päässeet nuolemaan akkuja, pattereita, lyijymaalipintoja tai moottoriöljyjä, joista ne voisivat nuolemalla saada lyijyä. Lisäksi niillä ei ole seuraavia lyijymyrkytyksen oireita: lihasväristykset, hikoilu,, hampaiden kirskutus, jäykkä leuka, hoipertelu, sokeus, laajentunut pupilla, työntyminen aitaa vasten, mania ja  kollapsi. Letaaliannos on nuorilla 200-400 mg/kg ja aikuisilla 600-800 mg/kg ja lyijystä imeytyy noin 2 %, ja loppu tulee ulosteen mukana pois. Lyijymyrkytys voisi tuskin koskaan aiheuttaa näin suurta kuolleisuutta isolla joukolla nautoja, vaan pikemminkin joillakin uteliailla yksilöillä ja enemmän epämääräisissä laidunolosuhteissa. ", task_id: 8},
  {exercise_id: 1, hypothesis_id: 11, explanation: "Lantakaasun myrkyllisin ja tappavin yhdiste on väritön rikkivety, jolla on voimakas mädäntyneen kananmunan haju. Rikkivety on vaarallinen soluhengitysmyrkky. Pienissä pitoisuuksissa se ärsyttää limakalvoja ja hengitysteitä aiheuttaen side- ja sarveiskalvon punoitusta ja tulehdusta. Altistuminen suuremmille pitoisuuksille aiheuttaa voimakkaan ärsytyksen lisäksi päänsärkyä, huimausta, heikkoutta ja sekavuutta. Altistuminen rikkivedylle 500 ppm:n (750 mg/m3) pitoisuudessa aiheuttaa viidessä minuutissa vakavia hermostollisia oireita ja tajuttomuutta, hengityskeskuksen lamaantumisen ja kuoleman jopa puolessa tunnissa. Yli 1 000 ppm:n (1 400 mg/m3) pitoisuus aiheuttaa välittömästi tajuttomuuden ja kuoleman hengityksen lamaannuttua. Tämä myrkytys voi syntyä, jos lietelannan pumppauksessa tapahtuu näiden kaasujen vapautumista hengitysilmaan. Tällä tilalla ei lietelantaa kuitenkaan ollut pumpattu näinä päivänä tai edes lähiaikoina ja lietelannan käsittelysysteemissä asia on otettu rakenteellisesti huomioon. Eläinsuojien sisäilmassa ei ollut havaittavissa vähäisintäkään outoa hajua. Tarvittaessa kaasupitoisuudet voisi mitata kaasunilmaisinlaitteilla, mutta nyt siihen ei ole mitään tarvetta.", task_id: 8},
  {exercise_id: 1, hypothesis_id: 21, explanation: "Lihanautoja ei ole laidunnettu, eivätkä ne ole saaneet järvivettä juodakseen.", task_id: 8},
  {exercise_id: 1, hypothesis_id: 20, explanation: "Omistajan mukaan tilalla ei ole ollut odottamattomia luonnonilmiöitä. Säätietojen mukaan paikkakunnalla ei ole ukkostanut. Eläimillä oli selkeitä oireita ennen kuolemaansa, mutta sähköisku tappaa heti.", task_id: 8},
  {exercise_id: 1, hypothesis_id: 15, explanation: "Piikki epidemiologisessa kuvaajassa ei viittaa tarttuvaan tautiin. Tarttuvassa taudissa sairastumisia ja kuolintapauksia ilmenee ryppäinä, joiden välillä tilanne voi näyttää normalisoituvan. Tilalle on tuotu uusia eläimiä teurastamoon lähteneiden tilalle, mutta ne eivät ole näin lyhyessä ajassa voineet aiheuttaa epidemiaa. Tarttuvan taudin oireiden ilmenemisen ja tartunnan tapahtumisen välillä on inkubaatioaika, joka voi sairaudesta riippuen olla pitkäkin. Lisäksi uudet eläimet on tuotu osastoihin 9, 10 ja 12, jotka sijaitsevat etäällä kuolleiden osastoista.", task_id: 10},
  {exercise_id: 1, hypothesis_id: 14, explanation: "", task_id: 18}
])
Hypothesis.create!([
  {name: "Aujeszkyn tauti", count: nil, hypothesis_group_id: 2},
  {name: "B-vitamiinin puutos", count: nil, hypothesis_group_id: 6},
  {name: "BSE", count: nil, hypothesis_group_id: 2},
  {name: "BVD (naudan virusripuli)", count: nil, hypothesis_group_id: 2},
  {name: "Botulismi-rehumyrkytys", count: nil, hypothesis_group_id: 3},
  {name: "Enteriitti", count: nil, hypothesis_group_id: 1},
  {name: "Hypertermia", count: nil, hypothesis_group_id: 4},
  {name: "IBR (naudan tarttuva rinotrakeiitti)", count: nil, hypothesis_group_id: 2},
  {name: "Kinokuume", count: nil, hypothesis_group_id: 2},
  {name: "Laidunkouristus (hypomagnesemia)", count: nil, hypothesis_group_id: 6},
  {name: "Lantakaasumyrkytys", count: nil, hypothesis_group_id: 3},
  {name: "Liika väkirehu", count: nil, hypothesis_group_id: 6},
  {name: "Lyijymyrkytys", count: nil, hypothesis_group_id: 3},
  {name: "Muu rehumyrkytys", count: nil, hypothesis_group_id: 3},
  {name: "Muu tarttuva tauti", count: nil, hypothesis_group_id: 1},
  {name: "Pernarutto", count: nil, hypothesis_group_id: 2},
  {name: "Pilaantunut rehu", count: nil, hypothesis_group_id: 6},
  {name: "Pneumonia", count: nil, hypothesis_group_id: 1},
  {name: "Poikimahalvaus (hypokalsemia)", count: nil, hypothesis_group_id: 6},
  {name: "Salamanisku tai muu odottamaton luonnonilmiö", count: nil, hypothesis_group_id: 5},
  {name: "Sinilevämyrkytys", count: nil, hypothesis_group_id: 3},
  {name: "Suu- ja sorkkatauti", count: nil, hypothesis_group_id: 2},
  {name: "Sähkölaitehäiriö (sähkö virtaa putkirakenteisiin) ja siitä johtuvat sähköiskut", count: nil, hypothesis_group_id: 4},
  {name: "Tetanus", count: nil, hypothesis_group_id: 1},
  {name: "Vierasesine rehussa ", count: nil, hypothesis_group_id: 5}
])
HypothesisGroup.create!([
  {name: "Infektiivinen tauti – muu kuin vastustettava"},
  {name: "Infektiivinen tauti – vastustettava"},
  {name: "Myrkytys"},
  {name: "Olosuhdeongelma"},
  {name: "Onnettomuus"},
  {name: "Ruokintahäiriö"}
])
Interview.create!([
  {title: "Epidemian ollessa kyseessä pitää tehdä tapausmääritelmä", subtask_id: 3},
  {title: "Omistajan haastattelu", subtask_id: 7},
  {title: "Kuolleisuuden tarkastelu", subtask_id: 9},
  {title: "Riskien tarkastelu", subtask_id: 10},
  {title: "Mihin ehkäiseviin ensitoimiin ryhdyt?", subtask_id: 12},
  {title: "Jatkoselvitystoimenpiteet", subtask_id: 18},
  {title: "Näytteiden tulokset", subtask_id: 19},
  {title: "Mitä jatkotoimia teet?", subtask_id: 22}
])
Multichoice.create!([
  {question: "Mietit, onko kyseessä epidemia", subtask_id: 1, is_radio_button: true},
  {question: "Otetaanko läänineläinlääkäriin yhteyttä?", subtask_id: 4, is_radio_button: true},
  {question: "Rehun käyttökieltovastausvalikko", subtask_id: 14, is_radio_button: false}
])
Option.create!([
  {multichoice_id: 1, content: "On", explanation: "Oikein, on kyseessä epidemia, koska tapauksia on tavallista enemmän.", is_correct_answer: "required"},
  {multichoice_id: 1, content: "Ei", explanation: "Yritä uudelleen!", is_correct_answer: "wrong"},
  {multichoice_id: 1, content: "En osaa sanoa", explanation: "Yritä uudelleen", is_correct_answer: "allowed"},
  {multichoice_id: 2, content: "Otan yhteyden läänineläinlääkäriin, koska epäilen lakisääteisesti vastustettavaa tautia", explanation: "Mieti uudestaan!", is_correct_answer: "wrong"},
  {multichoice_id: 2, content: "Neuvottelen kaiken varalta läänineläinlääkärin kanssa", explanation: "Oikein!", is_correct_answer: "required"},
  {multichoice_id: 2, content: "Ei tarvitse ottaa yhteyttä läänineläinlääkäriin", explanation: "Mieti uudestaan!", is_correct_answer: "wrong"},
  {multichoice_id: 3, content: "Heinä", explanation: "Yritä uudestaan. Katso RR- ja AR-lukuja", is_correct_answer: "wrong"},
  {multichoice_id: 3, content: "Juurikasmassa", explanation: "Käyttökielto tälle erälle, koska niillä, jotka söivät tätä rehua oli 32 kertaa suurempi riski kuolla kuin niillä, jotka eivät syöneet (RR). Lisäksi 97 % tätä rehua syöneiden kuolemista olisi voitu poistaa, jos eivät olisi syöneet juuri tätä rehua (AF). Tämä on siis suurin syyllinen kuolemiin.", is_correct_answer: "required"},
  {multichoice_id: 3, content: "Kivennäisrehu", explanation: "Yritä uudestaan. Katso RR- ja AR-lukuja", is_correct_answer: "wrong"},
  {multichoice_id: 3, content: "Melassileike", explanation: "Käyttökielto tälle erälle, koska niillä, jotka söivät tätä rehua oli 5 kertaa suurempi riski kuolla kuin niillä, jotka eivät syöneet (RR). Lisäksi 80 % tätä rehua syöneiden kuolemista olisi voitu poistaa, jos eivät olisi syöneet juuri tätä rehua (AF). ", is_correct_answer: "required"},
  {multichoice_id: 3, content: "Ohra", explanation: "Yritä uudestaan. Katso RR- ja AR-lukuja", is_correct_answer: "wrong"},
  {multichoice_id: 3, content: "Soijarouhe", explanation: "Yritä uudestaan. Katso RR- ja AR-lukuja", is_correct_answer: "wrong"},
  {multichoice_id: 3, content: "Säilörehu", explanation: "Yritä uudestaan. Katso RR- ja AR-lukuja", is_correct_answer: "wrong"},
  {multichoice_id: 3, content: "Vehnälese", explanation: "Käyttökielto tälle erälle, koska niillä, jotka söivät tätä rehua oli 7 kertaa suurempi riski kuolla kuin niillä, jotka eivät syöneet (RR). Lisäksi 85 % tätä rehua syöneiden kuolemista olisi voitu poistaa, jos eivät olisi syöneet juuri tätä rehua (AF).", is_correct_answer: "required"}
])
Question.create!([
  {title: "Tapaus on äkillisesti kuollut eläin", content: "Oikein. Tässä tapauksessa kannattaa lukea tähän kaikki kuolleet. Tapausmääritelmään luetellaan kaikki ne oireet, jotka oleellisia ja sitä voi tarkentaa vielä laboratoriotutkimusten jälkeen, mutta tässä pelissä näin ei tehdä. ", required: true, question_group_id: nil, interview_id: 1},
  {title: "Tapaus on tiettyjen oireiden jälkeen akuutisti kuollut eläin", content: "Oikein. Tässä tapauksessa kannattaa lukea tähän kuitenkin kaikki kuolleet. Tapausmääritelmään luetellaan kaikki ne oireet, jotka oleellisia ja sitä voi tarkentaa vielä laboratoriotutkimusten jälkeen, mutta tässä pelissä näin ei tehdä.", required: true, question_group_id: nil, interview_id: 1},
  {title: "Tapaus on tiettyjen pitkittyneiden oireiden jälkeen kuollut eläin", content: "Mieti uudestaan!", required: false, question_group_id: nil, interview_id: 1},
  {title: "Tapaus on tietyillä oireilla sairastunut eläin", content: "Mieti uudestaan!", required: false, question_group_id: nil, interview_id: 1},
  {title: "Tapaus on tietyillä oireilla sairastunut, mutta itsestään toipunut eläin ", content: "Mieti uudestaan!", required: false, question_group_id: nil, interview_id: 1},
  {title: "Tapaus on tietyillä oireilla sairastunut hoidolla toipunut eläin", content: "Mieti uudestaan!", required: false, question_group_id: nil, interview_id: 1},
  {title: "Ei mikään edellisistä", content: "Mieti uudestaan!", required: false, question_group_id: nil, interview_id: 1},
  {title: "Käsien pesu ja vaatteiden vaihto", content: "Hyvää hygieniaa on pyritty noudattamaan, kun kuljetaan osastoihin ja eri osastojen välillä .", required: false, question_group_id: 1, interview_id: 2},
  {title: "Eläinten siirrot", content: "Osastoista 9, 10 ja 12 eläimet lähtivät teuraaksi 8. elokuuta ja uudet eläimet näihin osastoihin saapuivat 10. elokuuta. Muuta eläinliikennettä tilalle/tilalta ei ole ollut ainakaan viikkoon.", required: true, question_group_id: 2, interview_id: 2},
  {title: "Tuontieläimet/onko eläimiä ostettu ulkomailta", content: "Tuontieläimiä ei ole. ", required: true, question_group_id: 2, interview_id: 2},
  {title: "Eläinsuojien ja muiden rakennusten sijoittelu tilalla", content: "Tilan pohjakartta lihanautatapaukseen", required: true, question_group_id: nil, interview_id: 2},
  {title: "Ilman laatu eläintiloissa", content: "Eläintiloissa on hyvä ilmanlaatu, ei erikoisia hajuja. Ilmastointi kunnossa.", required: true, question_group_id: 3, interview_id: 2},
  {title: "Juomavesi", content: "Osastojen 1-8 juomavesi tulee kunnallisesta vesijohdosta suoraan juottolaitteisiin. Sen laatu tutkitaan talousvedelle asetettavien vaatimusten mukaisesti. Osastojen 9-12 juomavesi tulee tilalla sijaitsevasta lähteestä. Lähde on pohjavesilähde, jota myös ihmiset käyttävät. Naudat ovat omissa osastoissaan, eivätkä pääse juomaan järvivettä.- Vaikka tässä tapauksessa vesi on kunnossa, niin kannattaa pitää mielessä, että kunnallista vettä tutkitaan erittäin harvoin yksittäisen tilan vesipisteestä, tehdyt tutkimukset kuvaavat verkostossa olevan veden laatua. Jos tila sijaitsee verkoston päässä, on mahdollista, että verkostosta tehty tutkimus ei vastaa nautojen juoman veden todellista laatua.", required: true, question_group_id: 3, interview_id: 2},
  {title: "Laidunnusolosuhteet", content: "Lihanautoja ei laidunneta, mutta niillä on jokaisen osaston yhteydessä riittävä romuvapaa mutta virikkeellinen ulkoilualue, joten ne eivät pääse järvivesien kanssa tekemisiin. Ulkoilualueet ovat sorapohjaisia (ei kasvillisuutta).", required: true, question_group_id: 3, interview_id: 2},
  {title: "Lietelannan käsittely", content: "Lietelanta ohjautuu osastoista poispäin, eikä sitä säilytetä osastojen alla. Lietelantavarastojen tyhjennyksessä noudatetaan varovaisuutta ja hyvää tuuletusta, eikä myrkyllisillä kaasuilla ole pääsyä takaisinpäin ja ilmanvaihto on toteutettu rakenteellisesti oikein. Lietelantavarastoa ei ole sekoitettu ja käsitelty viime aikoina, jolloin sieltä olisi voinut päästä myrkyllisiä rikkivetykaasuja.", required: true, question_group_id: 3, interview_id: 2},
  {title: "Tuotantoluvut", content: "Näkyykö näin akuutti tilanne vielä tuotantoluvuissa? Mieti uudestaan. Jos kyseessä olisi lypsykarjatila, maidontuotantomäärien selvittämisellä voisi olla merkitystä.", required: false, question_group_id: 3, interview_id: 2},
  {title: "Eläimistä otetut aikaisemmat laboratorio- tms. näytteet tai analyysit ", content: "Ei ole otettu muita näytteitä eläimistä.", required: false, question_group_id: 4, interview_id: 2},
  {title: "Rehuista otetut aikaisemmat näytteet tai  analyysit", content: "Rehuista on otettu normaalit ravintoarvoanalyysit, jotka kunnossa. Ei ole otettu muita näytteitä rehuista.", required: true, question_group_id: 4, interview_id: 2},
  {title: "Ihmisillä", content: "Isännän päätä oli särkenyt pari päivää, muita oireita ihmisillä ei ole huomattu.", required: true, question_group_id: 5, interview_id: 2},
  {title: "Muilla eläimillä", content: "Yhdellä koirista (bordercollie) on esiintynyt lievää syljeneristyksen lisääntymistä ja ripulia. Lisäksi sillä voidaan todeta lievähkö pupillojen supistuminen.", required: true, question_group_id: 5, interview_id: 2},
  {title: "Onko samanlaisia oireita ilmennyt aikaisemmin?", content: "Ei koskaan aikaisemmin. Eläimet eivät ole juuri sairastelleet.", required: true, question_group_id: 5, interview_id: 2},
  {title: "Rehujen säilytys", content: "Varasto A: Melassileike, soijarouhe, vehnälese, kivennäisrehu\r\nVarasto B: heinä ja juurikasmassa\r\nSiilot: Säilörehu ja ohra\r\nKaikki: Kaikki rehu sekoitetaan varastossa A, josta se jaetaan osastoihin traktorilla. Varastossa A säilytetään vain rehua ja rehusekoitinta.\r\nVarastossa B säilytetään rehujen lisäksi eläinten lääkkeitä (lukitussa kaapissa), kärpäsmyrkkyjä, kasvinsuojeluaineita ja loislääkkeitä (hyllyillä), maatalouskoneiden varaosia (hyllyillä), kasvinsuojeluaineita (hyllyillä) sekä eläintilojen puhdistukseen ja desinfiointiin käytettäviä aineita (hyllyillä).", required: true, question_group_id: 7, interview_id: 2},
  {title: "Säilörehun laatu ja pelto, josta se peräisin", content: "Säilörehu on tehty omalta pellolta ja siitä on tehty säännöllisesti rehuanalyysejä. Säilörehupellolla ei ole tehty suuria maanmuokkaustöitä ja koska se on hieman epätasainen, niittokorkeudeksi on säädetty 10 senttimetriä, mikä on selvästi normaalia korkeammalla. Säilörehu on lisäksi raikkaan hapokkaan tuoksuista, eikä siinä näy eläinten raatoja.", required: true, question_group_id: 7, interview_id: 2},
  {title: "Väkirehun laatu ", content: "Ei erityistä mainittavaa.", required: false, question_group_id: 7, interview_id: 2},
  {title: "Tilalla käytetyt rehut osastoittain", content: "Eläimet ovat eri osastoissa kasvatuksen eri vaiheissa (= eri-ikäisinä) ja saavat siksi rehua hiukan eri suhteissa. Rehuseoksen komponentit säilytetään kolmessa siilossa tai varastossa A ja B. Rehuseos valmistetaan päivittäin varaston A rehusekoittamossa. Tapahtuma-aikaan olivat käytössä seuraavanlaiset rehuseokset:", required: true, question_group_id: 7, interview_id: 2},
  {title: "Rehujen ostot ja vaihdokset", content: "Ei ostoja tai vaihdoksia.", required: true, question_group_id: 7, interview_id: 2},
  {title: "Koti- ja/tai tuotantoeläinten lääkehoidot ja ehkäisevät toimenpiteet", content: "Viimeisen kuukauden aikana eläimiä ei ole tarvinnut lääkitä muuten paitsi eilen, jolloin päivystävä eläinlääkäri kävi katsomassa oireilevia ja antoi niille magnesiumvalmisteita ja B-vitamiinia. Eläimiä ei ole rokotettu. Loishäätö on tehty viimeksi toukokuussa. Osastot 9, 10, ja 12 käsiteltiin kärpäsmyrkyllä (Neporex® WSG) 10.8", required: true, question_group_id: 8, interview_id: 2},
  {title: "Onko tilalla ollut koskaan pernaruttoa?  Onko haudattu pernaruttoon kuolleita elämiä?", content: "Isäntä ei tiedä, koska hän on ostanut tilan 10 vuotta sitten ihmiseltä, joka on jo kuollut.", required: true, question_group_id: 8, interview_id: 2},
  {title: "Sääolosuhteet", content: "Sääolosuhteista tietoa kaaviossa.", required: false, question_group_id: nil, interview_id: 2},
  {title: "Mitä eläimiä pitopaikassa on?", content: "Tilalla on kolme paimenkoiraa; kaksi australiankarjakoiraa ja yksi bordercollie. Tilalla ei ole muita tuotantoeläimiä kuin ko. lihanaudat.", required: true, question_group_id: 6, interview_id: 2},
  {title: "Ikä", content: "Naudat on jaettu osastoihin ikäryhmittäin:\r\nOsastot 1, 2, 6 ja 7: lähes teurasvalmiit naudat (12–15 kk).\r\nOsastot 3, 4, 5 ja 8: välivaiheen naudat (9-12 kk).\r\nOsastot 9-12: vasta välityksestä tulleet (6-9 kk).", required: true, question_group_id: 6, interview_id: 2},
  {title: "Rotu", content: "vaikuttaako rotu kuolleisuuteen tässä tapauksessa? Mieti uudestaan!", required: false, question_group_id: 6, interview_id: 2},
  {title: "Poikkeavat tapahtumat", content: "Osastot 9, 10, ja 12 kuivadesinfioitiin siihen tarkoitukseen sopivillaamvirtal ja käsiteltiin  10.8. kärpästen torjuntaan syromatsiinilla (Neporex® WSG, käsittelyn ajaksi eläimiä ei tarvitse siirtää pois).  Emännän mukaan tilalla ei ole muuten tapahtunut mitään erikoista tai poikkeavaa viime päivinä.", required: true, question_group_id: nil, interview_id: 2},
  {title: "Kuolleisuus rehuittain", content: "Attack rate, linkki epidemiologian käsitekortteihin. Taulukko, jossa tietoa, minkälaista rehua on syöty.", required: true, question_group_id: nil, interview_id: 3},
  {title: "Kuolintapauskartta", content: "Kuolintapauskartta-kuva sisältää tiedon, missä eläimiä on ja paljonko niitä on.", required: true, question_group_id: nil, interview_id: 3},
  {title: "Riskisuhteet, riskierot ja selitysosuudet rehujen vaikutuksesta kuolleisuuteen ", content: "Epidemiologiset assosiaatioluvut lihanaudoille -kuva sisältää tarvittavat tiedot.", required: true, question_group_id: nil, interview_id: 4},
  {title: "Hygienian tehostaminen", content: "Varmaan aina paikallaan, mutta on tärkeämpiäkin asioita.", required: false, question_group_id: nil, interview_id: 5},
  {title: "Karanteeni", content: "Mitä eläimiä tässä panisit karanteeniin?", required: false, question_group_id: nil, interview_id: 5},
  {title: "Lopetus", content: "Oikein, jos eläinsuojelulliset näkökohdat tai omistajan toivomus.", required: false, question_group_id: nil, interview_id: 5},
  {title: "Rajoittavat määräykset", content: "Epäiletkö lakisääteisesti vastustettavaa tautia?", required: false, question_group_id: nil, interview_id: 5},
  {title: "Rehun käyttökielto", content: "Valitse rehut, jotka laitetaan käyttökieltoon.", required: true, question_group_id: nil, interview_id: 5},
  {title: "Aikajanan piirtäminen", content: "Lihanautataudinpurkauksen aikajana -kuva.", required: true, question_group_id: nil, interview_id: 6},
  {title: "Epidemiologisen kuvaajan piirtäminen ", content: "Kuvaan epidemian kulkua ajan funktiona (linkki epidemiologian käsitekortteihin). Taulukkokuva vastaukseksi.", required: true, question_group_id: nil, interview_id: 6},
  {title: "Kollegoiden konsultoiminen", content: "Hyvä! Kollega myös tarjoaa vihjeen http://www.ava.com.au/sites/default/files/Investigating%20Sudden%20Death%20in%20Livestock_TIrwin.pdf Tämän linkin kautta ei siis ole pakko mennä, vaan sen voi myös ohittaa. Lisäksi opiskelijalle tulee vastaus ”kaikista taudinpurkaustapauksista ei automaattisesti ilmoiteta läänineläinlääkärille, mutta jos kuolleisuus on näinkin suuri eikä keskustelussa omistajan kanssa löydy selvää syytä kuolleisuudelle, kannattaa tapauksesta keskustella myös läänineläinlääkärin kanssa.", required: true, question_group_id: nil, interview_id: 6},
  {title: "Väliaikaraportin kirjoittaminen", content: "Hyvä juttu! Teen karjankasvattajalle väliaikaraportin, johon kirjaan kaikki tehdyt toimenpiteet ja ohjeet.", required: true, question_group_id: nil, interview_id: 6},
  {title: "Bakteriologia", content: "Lähetit kaiken varalta ennen kenttäobduktiota otetun verinäytteen taksilla Eviraan pernaruton varalta tutkittavaksi. Sen värjäys ja viljely ovat negatiivisia.", required: true, question_group_id: nil, interview_id: 7},
  {title: "Patologia", content: "Kokonaisen naudan tutkiminen patologisesti on arvokasta, koska pitää pohtia sen kuljettaminenkin. Ainoat ruumiinavauksessa todetut muutokset olivat keuhkoödeema. Kuolinsyyksi todettiin hengityksen vajaatoiminta. Patologiseen tutkimukseen lähetetyille näytteille tehdään tarvittaessa bakteeri- ja virustutkimukset.", required: true, question_group_id: nil, interview_id: 7},
  {title: "Toksikologia", content: "Atsinfossimetyylin hajoamistuotteita löytyi patologin eteenpäin lähettämistä kuolleen eläimen maksasta, munuaisista sekä mahansisällöstä. Lopullisten tulosten saaminen kestää noin viikon, koska elinnäytteet on lähetettävä ulkomaille. Juurikasmassan erässä 1, joka oli syötetty jo lähes loppuun, ei ollut havaittavia määriä tunnettuja myrkkyjä. Erässä 2, joka otettiin käyttöön 10. elokuuta, havaittiin korkeita pitoisuuksia atsinfossimetyyliä. \r\nAtsinfossimetyyli on organofosfaatti, jota on käytetty marjanviljelyksessä insektisidinä (mm. Gusation-ruiskutejauhe). LD50 rotalle po. on 4,4 -26 mg/kg. Rehun analyysi Evirassa kestää n. 3 päivää, kun se pyydetään kiireellisenä.", required: true, question_group_id: nil, interview_id: 7},
  {title: "Kuolleet haudataan", content: "Kyllä, mutta ruhot voi haudata vain alueilla, jotka on MMM asetuksessa määritelty syrjäisiksi alueiksi ja joista on kohtuuttoman pitkä matka Honkajoelle korkeariskisen eläinjätteen käsittelylaitokseen. Haudata saa myös Aluehallintoviraston (Avi) erityisluvalla.", required: false, question_group_id: nil, interview_id: 8},
  {title: "Kuolleet lähetetään Honkajoelle korkeariskisen eläinjätteen käsittelylaitokseen", content: "Kyllä!", required: true, question_group_id: nil, interview_id: 8},
  {title: "Kuolleiden tuhkaus", content: "Ei, tätä ei tehdä Suomessa tuotantoeläimille. Yritä uudestaan.", required: false, question_group_id: nil, interview_id: 8},
  {title: "Lopetus ja hautaus", content: "Kyllä, mutta ruhot voi haudata vain alueilla, jotka katsotaan syrjäseuduksi ja joista on kohtuuttoman pitkä matka Honkajoelle korkeariskisen eläinjätteen käsittelylaitokseen.", required: true, question_group_id: nil, interview_id: 8},
  {title: "Lopetus ja lähettäminen Honkajoelle korkeariskisen eläinjätteen käsittelylaitokseen", content: "Kyllä!", required: true, question_group_id: nil, interview_id: 8},
  {title: "Oireelliset lähetetään teurastamolle", content: "Sairaita ei saa lähettää teurastamolle, ei elävänä eikä kuolleena. Varmista, ettei tässä epidemiassa kuolleiden ruhoja ole joutunut odotteluaikana teurastamolle. Yritä uudestaan.", required: false, question_group_id: nil, interview_id: 8},
  {title: "Oireettomia lähetetään teurastamolle", content: "Eläimiä ei ole suositeltavaa lähettää teuraaksi tämän epidemian aikana ennen kuolinsyyn selviämistä, vaikkei rajoittavia määräyksiä ole annettukaan. Ja muista, että sairaita ei saa lähettää teurastamolle, ei elävänä eikä kuolleena.  \r\nKoska tässä tapauksessa on vaaraa, että elintarvikekäyttöä varten kasvatettavien eläinten lihassa olisi jäämiä vieraasta aineesta (kasvinsuojeluainejäämiä), tulee eläinlääkärin olla asiasta yhteydessä kunnan elintarvikevalvontaviranomaiseen, joka selvittää kyseisen aineen osalta tarvittavat jatkotoimenpiteet ja tutkimusmahdollisuudet. Yritä uudestaan.", required: false, question_group_id: nil, interview_id: 8},
  {title: "Omistajan ohjeistus", content: "Kyllä!", required: true, question_group_id: nil, interview_id: 8},
  {title: "Omistajan ohjaaminen saamaan tukea", content: "Kyllä!", required: true, question_group_id: nil, interview_id: 8},
  {title: "Korvaushakemusten pohtiminen", content: "Kyllä, mutta tässä tapauksessa tuskin saa korvauksia mistään, koska rehut ovat mitä ilmeisimmin päässeet kontaminoitumaan myrkyllä omassa rehuvarastossa. Omistajaa kannattaa kuitenkin neuvoa olemaan yhteydessä vakuutusyhtiöönsä vakuutusturvansa selvittämiseksi.", required: true, question_group_id: nil, interview_id: 8},
  {title: "Näytetulosten mukainen hoito", content: "Atsinfossimetyylimyrkytyksen hoito. Atsinfossimetyyli on koliiniesteraasi-inhibiittori ja saa aikaan kolinergisiä oireita, kuten syljeneritystä ja kyyneleritystä ja voi johtaa hengityksen pysähtymiseen. Atsinfossimetyylin LD50  on rotalle po 4,4-26 mg/kg.  Kolinergisen oireet alkavat yleensä 5 minuuttia - 2 vrk kuluttua nauttimisesta. Kuolema tai täydellinen toipuminen tapahtuu yleensä 24 tunnin kuluessa kliinisten oireiden ilmaantumisesta. Ihmiselle lievä altistus hengitysteiden kautta aiheuttaa päänsärkyä, mutta muuten on myrkyllinen myös ihmiselle.\r\nHoitona atropiini-injektiot (annos 0,25 mg/kg, josta 1/3 hitaasti i.v ja loput i.m., toistetaan 4-5 h välein 1-2 vrk). Atropiini inj. 1 mg/ml, pakkaus 25 x 1 ml n. 95 e. Jos lihakarjarotuinen lehmä painaa 500–900 kg ja sonni 800–1400 kg, hoito maksaa (linkki vapaaehtoinen eli sen voi ohittaa):\r\nMyrkytyksen alkuvaiheessa lisänä voi käyttää pralidoksiimia tai obidoksiimia, jotka ovat erityislupavalmisteita ja joita ei nopeasti saa mistään.\r\nHoitona annetaan vielä hiiltä per os, kouristusten hoito sedatiiveilla ja anesteeteilla.\r\nMUTTA TÄMÄN HOIDON KUSTANNUKSET OLISIVAT MELKOISET:\r\nKeskikokoinen lehmä tai pieni sonni: 0,25 mg/kg x 800 kg = 200 mg, tämä on vasta yksi annos/per eläin. Jos hoito toistettaisiin 4 tunnin välein ja vuorokaudessa on 24 tuntia, se tarkoittaisi 6 kertaa jo yhden vuorokauden aikana ja 12 kertaa 2 vuorokauden aikana = 1200 mg/1 vuorokausi, 2400 mg/2 vuorokautta. Atropiini- injektiossa on 1mg/ml ja vuorokaudessa tarvitaan 1200 mg. Yhdessä 95 euron hintaisessa pakkauksessa on 25 mg/ml ja tarvitaan 1200 mg. Silloin tarvittaisiin 48 pakkausta, jonka kokonaishinta tulisi olemaan 4560e. Ja tämä hinta on laskettu vasta yhdelle eläimelle yhden vuorokauden annoksella… joten lopettaminen olisi parempi vaihtoehto, ellei pelkkä tukeva hoito riitä, koska joku yksilö voi toipua. Mutta eläinsuojelulliset näkökohdat on otettava huomioon.", required: true, question_group_id: nil, interview_id: 8},
  {title: "Epidemiologinen selvitys, ellei ole tehty aikaisemmin", content: "Kyllä, pitää tarkistaa, ovatko muut eläimet saaneet tartuntaa, onko eläinten tuoja toiminat asianmukaisesti ja onko koko tuontiprosessi asianmukainen.", required: false, question_group_id: nil, interview_id: 8},
  {title: "Yleinen informaatio/valistus", content: "Pohdittava, onko tarpeen omalla toimialueella.", required: false, question_group_id: nil, interview_id: 8}
])
QuestionGroup.create!([
  {title: "Bioturvallisuus", interview_id: 2},
  {title: "Eläinliikenne", interview_id: 2},
  {title: "Eläinten ja pitopaikan hoitaminen", interview_id: 2},
  {title: "Näytteet", interview_id: 2},
  {title: "Oireet", interview_id: 2},
  {title: "Pitopaikan eläimet ja käyttötarkoitus", interview_id: 2},
  {title: "Ruokinta", interview_id: 2},
  {title: "Sairaus- ja hoitohistoria", interview_id: 2}
])
Task.create!([
  {name: "Epidemia vai ei", exercise_id: 1, level: 1},
  {name: "Lisätietoa puhelimessa", exercise_id: 1, level: 2},
  {name: "Työhypoteesilista", exercise_id: 1, level: 3},
  {name: "Tapausmääritelmä", exercise_id: 1, level: 4},
  {name: "Yhteydenotto läänineläinlääkäriin", exercise_id: 1, level: 5},
  {name: "Lisätietoa kysymyksillä kliinisen tutkimuksen yhteydessä", exercise_id: 1, level: 5},
  {name: "Kliininen tutkimus", exercise_id: 1, level: 5},
  {name: "Tapausten kartoitusta", exercise_id: 1, level: 6},
  {name: "Kenttäobduktio", exercise_id: 1, level: 7},
  {name: "Ehkäisevät ensitoimet ", exercise_id: 1, level: 7},
  {name: "Hoito", exercise_id: 1, level: 7},
  {name: "Näytteenotto tutkimuksiin", exercise_id: 1, level: 8},
  {name: "Jatkoselvitys", exercise_id: 1, level: 8},
  {name: "Näytteiden tulokset", exercise_id: 1, level: 9},
  {name: "Mikä on diagnoosisi?", exercise_id: 1, level: 10},
  {name: "Jatkotoimet", exercise_id: 1, level: 11},
  {name: "Loppuratkaisu", exercise_id: 1, level: 12}
])
Subtask.create!([
  {task_id: 3, level: 9},
  {task_id: 4, level: 9},
  {task_id: 6, level: 9},
  {task_id: 7, level: 9},
  {task_id: 7, level: 10},
  {task_id: 7, level: 11},
  {task_id: 8, level: 8},
  {task_id: 9, level: 6},
  {task_id: 10, level: 5},
  {task_id: 10, level: 6},
  {task_id: 11, level: 4},
  {task_id: 12, level: 4},
  {task_id: 12, level: 5},
  {task_id: 12, level: 6},
  {task_id: 13, level: 4},
  {task_id: 14, level: 3},
  {task_id: 15, level: 3},
  {task_id: 15, level: 4},
  {task_id: 16, level: 3},
  {task_id: 17, level: 3},
  {task_id: 18, level: 2},
  {task_id: 18, level: 3},
  {task_id: 19, level: 2},
  {task_id: 5, level: 2}
])
TaskText.create!([
  {content: "Oireet lihanaudoille: Omistaja kertoo vielä puhelimessa, että eilen (10. elokuuta) illalla useilla eläimillä eri osastoissa oli seuraavia oireita: supistuneet pupillat, voimistunut syljeneritys, kyynelvuoto, lisääntynyt virtsaaminen, koliikki, horjuva kävely ja kouristukset. Ensimmäiset kuolleet todettiin 11. elokuuta. Päivystävä eläinlääkäri kävi silloin hoitamassa oireilevia. Hän oli epäillyt hypomagnesemiaa ja B-vitamiinin puutosta sekä antanut näiden mukaisen hoidon (Parevet-liuosta ja Sedamania koon mukaan annostellen, B-vitamiinia). Oireilleiden määrää omistaja ei puhelimessa muistanut, mutta lääkityksellä ei kuitenkaan ollut vaikutusta eläimiin, koska nyt niitä on kuollut.", subtask_id: 2},
  {content: "Kaikista taudinpurkaustapauksista ei automaattisesti ilmoiteta läänineläinlääkärille, mutta koska tässä tapauksessa on näin korkea kuolleisuus, kannattaa asiasta neuvotella läänineläinlääkärin kanssa.", subtask_id: 5},
  {content: "Lisää tietoja voit lukea eläintautilain 3. luvusta: http://www.finlex.fi/fi/laki/alkup/2013/20130441#Pidp1255920", subtask_id: 6},
  {content: "Teet kliinisen tutkimuksen ja toteat, että tutkimushetkellä (11. elokuuta) tilalla ei ollut kuumeisia eläimiä, mutta useilla eläimillä oli kyynelvuotoa ja voimistunutta syljeneritystä. Haastattele omistajaa.", subtask_id: 8},
  {content: "Koska oireet eivät viitanneet pernaruttoon, suoritit kenttäobduktion ja koska avaamissasi muutamissa ruhoissa ei ollut myöskään merkkejä pernarutosta eli perna ja maksa eivät olleet suurentuneita ja verisiä, obduktiota voitiin myös jatkaa. Et havainnut vierasesineitä. Keuhkot vaikuttivat raskaammilta kuin tavallisesti.", subtask_id: 11},
  {content: "Kiellän käyttämästä seuraavia rehuja ”Riskisuhteet, riskierot ja selitysosuudet rehujen vaikutuksesta kuolleisuuteen” –laskelmieni perusteella:", subtask_id: 13},
  {content: "Tässä vaiheessa voi oireilevia hoitaa vain tukea antavasti, koska ei ole tietoa aiheuttajasta.", subtask_id: 15},
  {content: "Mieti ensin, mitä lähteät näytteeksi ja mitä näytteestä tutkitaan. Näytteiden ottaminen voi myös olla kallista, joten mieti tarkkaan, mitä näytteitä haluat ottaa. Seuraavaksi päätä, minne näyte lähetetään ja miten se lähetetään. Näytteet pitää lähettää oikealla menetelmällä oikeaan paikkaan. Näytteiden tulosten saaminen saattaa kestää kauan.", subtask_id: 16},
  {content: "Jos olet ottanut jo näytteet, mieti, mitä teet näytteenoton tuloksia odotellessasi.", subtask_id: 17},
  {content: "Mikä on diagnoosisi saamiesi lisätietojen jälkeen? Jos et vielä ole varma diagnoosistasi, voit vilkaista kollegaltasi saamia lisätietoja: http://www.ava.com.au/sites/default/files/Investigating%20Sudden%20Death%20in%20Livestock_TIrwin.pdf ", subtask_id: 20},
  {content: "Tällaisessa tapauksessa omistaja usein haluaa tietää, mitä kuolleille tehdään? Entä oireilleille, jotka lopetettiin ja jotka ovat olleet odottamassa lopullisia tuloksia? Mitä vastaat omistajalle? Entä mitä muuta teet omistajan kanssa?", subtask_id: 21},
  {content: "Seuraavaksi pääset tarkastelemaan ratkaisuesitystä caseen Taudinpurkaus lihanautakasvattamossa.", subtask_id: 23},
  {content: "Mitä työhypoteeseja sinulle on puhelinkeskustelun perusteella muodostunut? \r\nTilalla on: infektiivinen tauti – lakisääteisesti vastustettava, infektiivinen tauti – muu kuin lakisääteisesti vastustettava, ruokintahäiriö, olosuhdeongelma, myrkytys, onnettomuus? Käy Työhypoteesit-välilehdellä poissulkemassa sopivia diagnooseja.\r\n", subtask_id: 24}
])
User.create!([
 {username: "Opettaja", admin: true, email: "ope@ope.fi", realname: "Opettaja", password_digest: "$2a$10$6vsU8Cs5Drx5zoJIVGHqfuBKOc9Hs1FD/EtsJM90eDR6cK/ZPRdCm"},
 {username: "Opiskelija", admin: false, email: "opiskelija@opiskelija.fi", realname: "Opiskelija", password_digest: "$2a$10$irUogp6GtW.sshj/qoS4K.YmDLPs02j7ALo7Lsn7xKGFMzEg5Gg1a"},
 {username: "Oppilas", admin: false, email: "oppilas@oppilas.fi", realname: "Oppilas", password_digest: "$2a$10$uxWqK7.yB7AqMMIcx8r0FeCxaFEZ3/MJ/VNLDmvxVAPxZxK6HMCNa"}
])